import { JSONSchema4 } from 'json-schema';
import { endsWith, merge } from 'lodash';
import { format, Options as PrettierOptions } from 'prettier';
import { generate } from './generator';
import { normalize } from './normalizer';
import { parse } from './parser';
import { dereference } from './resolver';
import { validate } from './validator';

export interface Options {
  /**
   * Disclaimer comment prepended to the top of each generated file.
   */
  bannerComment: string;
  /**
   * Root directory for resolving [`$ref`](https://tools.ietf.org/id/draft-pbryan-zyp-json-ref-03.html)s.
   */
  cwd: string;
  /**
   * Generate code for `definitions` that aren't referenced by the schema?
   */
  unreachableDefinitions: boolean;
}

export const DEFAULT_OPTIONS: Options = {
  bannerComment: ` /**
* This file was automatically generated by Slyp's json-schema to typescript generator.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the generator to regenerate this file.
*/`,
  cwd: process.cwd(),
  unreachableDefinitions: false
};

export async function compile(schema: JSONSchema4, name: string, options: Partial<Options> = {}): Promise<string> {
  const _options = merge({}, DEFAULT_OPTIONS, options);

  const errors = validate(schema, name);
  if (errors.length) {
    errors.forEach(console.error);
    throw new Error();
  }

  // normalize options
  if (!endsWith(_options.cwd, '/')) {
    _options.cwd += '/';
  }

  const code: string = generate(parse(await dereference(normalize(schema, name), _options.cwd), _options), _options);
  const stypeOptions: PrettierOptions = {
    bracketSpacing: false,
    printWidth: 80,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: 'none',
    useTabs: false
  };
  return format(code, { parser: 'typescript', ...stypeOptions });
}

export class ValidationError extends Error {}
